export const theme = {
  colors: {
    background0: '#FFFFFF',
    background05: '#F5F4F5',
    background1: '#EAEAEB',
    background2: '#D6D4D6',
    background3: '#C1BFC2',
    background4: '#ADA9AD',
    background5: '#989499',
    background6: '#5C5A5D',
    background7: '#3F3D3F',
    background8: '#212021',
    background9: '#030303',
    fighting: '#b44d54',
    fire: '#d36255',
    electric: '#ebd56c',
    ground: '#d3ae6b',
    normal: '#d1d2c0',
    rock: '#a49d9a',
    steel: '#78817e',
    dark: '#3d413f',
    grass: '#9baf65',
    bug: '#c6d282',
    ice: '#c6fbf9',
    water: '#3cafe8',
    flying: '#a2bfeb',
    dragon: '#b7b6db',
    fairy: '#e8a9d3',
    psychic: '#db6ab5',
    poison: '#9756dc',
    ghost: '#655a7d',
  },
  typography: {
    display1: {
      desktop: {
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '28px',
        lineHeight: '40px',
      },
      mobile: {
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '24px',
        lineHeight: '32px',
      },
    },
    headline: {
      desktop: {
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '24px',
        lineHeight: '32px',
      },
      mobile: {
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '20px',
        lineHeight: '28px',
      },
    },
    subheadline: {
      desktop: {
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '18px',
        lineHeight: '24px',
      },
      mobile: {
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '16px',
        lineHeight: '20px',
      },
    },
    body: {
      desktop: {
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '16px',
        lineHeight: '20px',
      },
      mobile: {
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '16px',
        lineHeight: '20px',
      },
    },
    link: {
      desktop: {
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '16px',
        lineHeight: '20px',
      },
      mobile: {
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '14px',
        lineHeight: '18px',
      },
    },
    caption: {
      desktop: {
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '12px',
        lineHeight: '16px',
      },
      mobile: {
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '12px',
        lineHeight: '16px',
      },
    },
  },
  breakpoints: {
    mobile: '768px',
  },
  shadows: {
    s: {
      'box-shadow': `0px 5px 10px -2px rgba(125, 59, 236, 0.15), 0px 2px 3px -1px rgba(125, 59, 236, 0.07)`,
      'border-radius': '16px',
    },
    m: {
      'box-shadow': `0px 10px 15px -3px rgba(125, 59, 236, 0.1), 0px 4px 6px -2px rgba(125, 59, 236, 0.05)`,
      'border-radius': '16px',
    },
    l: {
      'box-shadow': `0px 15px 20px -5px rgba(125, 59, 236, 0.1), 0px 6px 8px -3px rgba(125, 59, 236, 0.05)`,
      'border-radius': '16px',
    },
  },
  radius: {
    '2xs': '4px',
    xs: '8px',
    s: '12px',
    m: '16px',
    l: '20px',
    xl: '24px',
    '2xl': '32px',
  },
  spacing: {
    '3xs': '2px',
    '2xs': '4px',
    xs: '8px',
    s: '12px',
    m: '16px',
    l: '20px',
    xl: '24px',
    '2xl': '32px',
    '3xl': '32px',
    '4xl': '32px',
  },
};
